services:
    remote:
        image: ghcr.io/mitchellthompkins/embedded_sdk:latest
        extends:
          file: docker-compose-base.yaml
          service: base

    local-amd64:
        image: embedded_sdk-amd64:latest
        extends:
          file: docker-compose-base.yaml
          service: base

    local-arm64:
        image: embedded_sdk-arm64:latest
        extends:
          file: docker-compose-base.yaml
          service: base
