services:
  base:
    environment:
        - USER=${USER}
        - MY_UID=${MY_UID:? Error -> need UID.}
        - MY_GID=${MY_GID:? Error -> need GID.}
    volumes:
        - "${PWD}:${PWD}"
    network_mode: host
    tty: True
    working_dir: ${PWD}
    entrypoint: ${PWD}/entrypoint.sh
    command: /bin/bash
